server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://124.223.15.205:33306/dome?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    password: eXfkpHhY5HFAvp9G
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最大连接池数量
      maximum-pool-size: 20
      # 最小空闲线程数量
      minimum-idle: 10
      # 配置获取连接等待超时的时间
      connection-timeout: 30000
      # 校验超时时间
      validation-timeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 连接测试query（配置检测连接是否有效）
      connection-test-query: SELECT 1
      # 多久检查一次连接的活性
      keepalive-time: 30000
  main:
    banner-mode: console
  data:
    redis:
      database: 10
      host: 124.223.15.205
      port: 36379
      password: rzDX32tGoA3Z1go7
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  #文件存储配置
  file-storage:
    #默认使用的存储平台
    default-platform: tencent-cos-1
    #缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".jpg"
    # 腾讯云 COS
    tencent-cos:
      # 存储平台标识
      - platform: tencent-cos-1
        # 启用存储
        enable-storage: true
        secret-id: AKIDs2BB1cx85pNtKZjsrpeNUn9OflngPwPi
        secret-key: CID5lFZrxsgP1X1Red2JNG9oFTVYSAgz
        #存仓库所在地域
        region: ap-chengdu
        bucket-name: blog-1310216282
        # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
        domain: https://blog-1310216282.cos.ap-chengdu.myqcloud.com/
        base-path: blog/ # 基础路径
  storage:
    bucket-name: blog-1310216282
    region: ap-chengdu
    domain: https://blog-1310216282.cos.ap-chengdu.myqcloud.com/
    secretId: AKIDs2BB1cx85pNtKZjsrpeNUn9OflngPwPi
    secretKey: CID5lFZrxsgP1X1Red2JNG9oFTVYSAgz
  #文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB


mybatis-plus:
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: net.lh.dome.**.domain
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location: false
  configuration:
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    auto-mapping-behavior: partial
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    auto-mapping-unknown-column-behavior: none
  global-config:
    db-config:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type: AUTO
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      # IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insert-strategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      update-strategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name:  ization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# 日志配置
logging:
  level:
    com.lh.dome: debug
    org.springframework: info