server:
  port:
  servlet:
    context-path:

spring:
  datasource:
    url:
    password:
    username:
    driver-class-name:
    hikari:
      # 最大连接池数量
      maximum-pool-size:
      # 最小空闲线程数量
      minimum-idle:
      # 配置获取连接等待超时的时间
      connection-timeout:
      # 校验超时时间
      validation-timeout:
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout:
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime:
      # 连接测试query（配置检测连接是否有效）
      connection-test-query:
      # 多久检查一次连接的活性
      keepalive-time:
  redis:
    host:
    port:
    password:
    timeout:
    jedis:
      pool:
        max-active:
        max-wait:
        max-idle:
        min-idle:
  main:
    banner-mode:
  data:
    redis:
      database:
      host:
      port:
      password:
      timeout:
      lettuce:
        pool:
          # 连接池最大连接数
          max-active:
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait:
          # 连接池中的最大空闲连接
          max-idle:
          # 连接池中的最小空闲连接
          min-idle:
  #文件存储配置
  file-storage:
    #默认使用的存储平台
    default-platform:
    #缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".jpg"
    # 腾讯云 COS
    tencent-cos:
      # 存储平台标识
      - platform:
        # 启用存储
        enable-storage:
        secret-id:
        secret-key:
        #存仓库所在地域
        region:
        bucket-name:
        # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
        domain:
        base-path:  # 基础路径
  storage:
    bucket-name:
    region:
    domain:
    secretId:
    secretKey:
  #文件上传大小
  servlet:
    multipart:
      max-file-size:
      max-request-size:

minio:
  #minio部署的机器ip地址
  endpoint:
  #minio使用的端口
  port:
  #唯一标识的账户
  accessKey:
  #账户的密码
  secretKey:
  #是否使用https
  secure:
  #测试使用的桶名称
  defaultBucketName:
  #捅名称
  bucketName:

mybatis-plus:
  # 对应的 XML 文件位置
  mapper-locations:
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  check-config-location:
  configuration:
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case:
    # MyBatis 自动映射策略
    # NONE：不启用 PARTIAL：只对非嵌套 resultMap 自动映射 FULL：对所有 resultMap 自动映射
    auto-mapping-behavior:
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    auto-mapping-unknown-column-behavior:
  global-config:
    db-config:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      id-type:
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      # IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insert-strategy:
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      update-strategy:
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy:

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name:
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout:
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout:
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent:
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share:
  # token风格
  token-style:
  # 是否输出操作日志
  is-log:

# 日志配置
logging:
  level:
    com.lh.dome:
    org.springframework: